# name = "v20251104"
# wrangler.toml
name = 'itrack'
main = "_worker.js"
compatibility_date = "2025-12-25"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id

